idf_component_register(
    SRCS
        "main.c"
        "radio_font.c"
        "radio_screen.c"
        "radio_stream.c"
        "weather_service.c"
        "weather_icons.c"
    INCLUDE_DIRS "."
    EMBED_FILES
        "radio_font.bin"
        "weather_icons.bin"
    PRIV_REQUIRES
        driver
        esp_audio_codec
        esp_event
        esp_hw_support
        esp_http_client
        esp_partition
        esp_netif
        mbedtls
        esp_wifi
        lvgl
        nvs_flash
        cjson
)
